### ISSUE TITLE
Internal error on command:"SYNC_MOTORS"

### ISSUE THREAD

**Issue by FlorentBroise** [MRX8024/motors-sync#5]
![image](https://github.com/MRX8024/motors-sync/assets/93141411/346e6f0f-6996-4362-b29f-60e637693fb8)

Hi
Got this issue after a full proper installation
Maybe you will be able to guide me ;) I'd love to see this mod to work ;)

Thanks in advance

[klippy (2).log](https://github.com/user-attachments/files/16073981/klippy.2.log)

**Comment by MRX8024** [comment]
Hi, thanks for the feedback. I just noticed the same issue from a month ago, due to the lack of notifications. I see you already solved the problem without me and suggested pr. Honestly, I thought that Python can automatically convert float to int like jinja2 does for example :) I think I'll rewrite this function today in a better way, wait for the news!

-Maxim

**Comment by MRX8024** [comment]
Well, I fixed the problem. 
Thanks again, if you have no questions or wishes, I think we can close this issue and pr.

-Maxim

**Comment by FlorentBroise** [comment]
Thanks a lot! Working like a charm now :)
